[fprime]
project_root: .
framework_path: ./lib/fprime
library_locations: ./lib/fprime-zephyr:./lib/fprime-stm32h7-zephyr

# Default platform is zephyr, but can be overridden with --platform flag
default_toolchain: zephyr

# Zephyr/STM32H7 configuration
[zephyr]
cmake_options: FPRIME_ENABLE_FRAMEWORK_UTS=OFF
               FPRIME_ENABLE_AUTOCODER_UTS=OFF
               BOARD=nucleo_h723zg
               # BOARD=stm32h753i_eval

# Linux/Raspberry Pi configuration  
[linux]
cmake_options: FPRIME_ENABLE_FRAMEWORK_UTS=OFF
               FPRIME_ENABLE_AUTOCODER_UTS=OFF
